config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :cards
  post 'home' => 'home#compare'

  resources :users
  resources :user_sessions

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/card.rb
class EqualValidator < ActiveModel::Validator
  def validate(card)
    if card
      if card.original_text.mb_chars.downcase.strip.normalize == card.translated_text.mb_chars.downcase.strip.normalize
        card.errors[:base] << 'The values of original text and translated text should be different'
      end
    end
  end
end

class Card < ActiveRecord::Base
  belongs_to :user

  has_attached_file :avatar, styles: { medium: '360x360>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def set_review_date
    self.review_date = Date.current + 3.days
  end

  scope :select_cards_for_learning, -> (u) { where('review_date <= ? AND user_id = ?', Time.now, u).order('RANDOM()') }
  scope :select_cards_by_user_id, -> (u) { where('user_id = ?', u) }

  def check_translation(mytext)
    translated_text.mb_chars.downcase.strip == mytext.mb_chars.downcase.strip
  end

  before_validation :set_review_date
  validates :original_text, :translated_text, :review_date, :user_id, presence: true
  validates_with EqualValidator
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cards, dependent: :destroy
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes['password'] }
  validates :password, confirmation: true, if: -> { new_record? || changes['password'] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes['password'] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :require_login
  def index
    @cards = Card.select_cards_by_user_id(current_user.id)
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = current_user.cards.new
  end

  def edit
    @card = Card.find(params[:id])
  end

  def create
    @card = current_user.cards.create(cards_params)
    @card.save!
    redirect_to @card
  end

  def update
    @card = Card.find(params[:id])
    if @card.update(cards_params)
      redirect_to @card
    else
      render 'edit'
  end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to cards_path
  end

  private

  def require_login
    redirect_to new_user_path unless current_user
  end

  def cards_params
    params.require(:card).permit(:original_text, :translated_text, :review_date, :user_id, :avatar)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @card = current_user.cards.first unless current_user.nil?
   end

  def compare
    @card = Card.find(params[:card_id])
    if @card.check_translation(params[:user_variant])
      @card.set_review_date
      @card.save!
      flash[:notice] = true
    else
      flash[:error] = true
    end
    redirect_to '/'
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(users_params)
    @user.save!
    redirect_to @user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(users_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= form_for @card do |f| %>
<p>
  <%= f.label :original %><br>
  <%= f.text_field :original_text %>
</p>

<p>
  <%= f.label :translate %><br>
  <%= f.text_field :translated_text %>
</p>

<p>
  <%= f.file_field :avatar %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/cards/create.html.erb
<h1>New card was created</h1>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Listing cards</h1>
<table>
  <tr>
    <th>Original Text</th>
    <th>Translated Text</th>
		<th>Review Date</th>
    <th>User</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
 
  <% @cards.each do |card| %>
    <tr>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.strftime("%d/%m/%Y") %></td>
      <td><%= card.user_id %></td>
      <td><%= image_tag card.avatar.url(:medium) %></td>
      <td><%= link_to 'Show', card_path(card) %></td>
      <td><%= link_to("Edit", edit_card_path(card) ) %></td>
      <td><%= link_to("Delete",card_path(card), method: :delete, data: { confirm: 'Are you sure?' }) %></td>
    </tr>
  <% end %>

</table>

app/views/cards/new.html.erb
<h1>New cards</h1>

<%= render 'form' %>
<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<head>
  <title>Cards</title>
  <link rel="stylesheet" href="application.css">
</head>

<table>

    <tr>
	    <th>Original Text</th>
	    <th>Translated Text</th>
	    <th>Review Date</th>
      <th>Picture</th>

    </tr>

    <tr>
      <td><%= @card.original_text %></td>
      <td><%= @card.translated_text %></td>
      <td><%= @card.review_date.strftime("%d/%m/%Y") %></td>
      <td> <%= image_tag @card.avatar.url(:medium) %></td>
    </tr>

</table>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>




app/views/home/index.html.erb
<section id="container">
  <header class="clearfix">
    <h1>Флэшкарточкер</h1>
    <ul class="navigation-links">
      <li><%= link_to 'Все карточки', cards_path %></li>
      <li><%= link_to 'Добавить карточку', new_card_path %></li>
      </ul>
  </header>

  <section>
    <p style="font-size: 22px;">
      Первый в мире удобный менеджер флеш-карточек. Именно так.
    </p>
  </section>
</section>

<% if flash[:notice] %>
 <p class="notice">Правильно!</p>
<% end %>

<% if flash[:error] %>
  <p class="error">Ошибка!</p>
<% end %>

<% if @card.present? %>
  <%= form_tag home_path do %>
    <%= text_field_tag :user_variant%>
    <%= hidden_field_tag 'card_id', @card.id %>
    <%= image_tag @card.avatar.url(:medium) %>
		<button>Проверить!</button>
	<% end %>
  <table>
    <tr>
      <th>Original Text</th>
      <th>Translated Text</th>
      <th>Review Date</th>
    </tr>
    <tr>
      <td><%= @card.original_text %></td>
      <td><%= @card.translated_text %></td>
      <td><%= @card.review_date.strftime("%d/%m/%Y") %></td>
    </tr>
  </table>
<% end %>

app/views/layouts/application.html.erb
<head>
  <title>Флэшкарточкер</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
</head>

<%= javascript_include_tag 'application' %>

    <% if current_user %>
      <%= link_to "Edit Profile", edit_user_path(current_user.id) %>
      <%= link_to "Logout", :logout, method: :post %>
    <% else %>
      <%= link_to "Register", new_user_path %> |
      <%= link_to "Login", :login %>
    <% end %>

    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>

<%= yield %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>

  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>

  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>

  <div>
    <%= check_box_tag :remember, params[:remember], true %>
    <%= label_tag :remember %>
  </div>

  <div class="actions">
    <%= submit_tag "Login" %>
  </div>

<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<p>
  <%= f.label :email %><br>
  <%= f.email_field :email, :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' %>
</p>

<p>
  <%= f.label :password %><br>
  <%= f.password_field :password, :required => true %>
</p>

<p>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation, :required => true %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/users/create.html.erb
<h1>New user was created</h1>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<head>
  <title>Users</title>
  <link rel="stylesheet" href="application.css">
</head>

<table>

  <tr>
    <th>Email</th>
    <th>Password</th>
  </tr>

  <tr>
    <td><%= @user.email %></td>
    <td><%= @user.password %></td>
  </tr>

</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Home', root_path %>

